#!/usr/bin/env node

/**
 * ABI Generation Script
 * Reads deployed contract from fhevm-hardhat-template/deployments
 * and generates TypeScript ABI and address files for frontend
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FRONTEND_ROOT = path.resolve(__dirname, '..');
const HARDHAT_ROOT = path.resolve(FRONTEND_ROOT, '..', 'fhevm-hardhat-template');
const DEPLOYMENTS_DIR = path.join(HARDHAT_ROOT, 'deployments');
const OUTPUT_DIR = path.join(FRONTEND_ROOT, 'abi');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('🔨 Generating ABI files...');

// Read deployments from both networks
const localhostPath = path.join(DEPLOYMENTS_DIR, 'localhost', 'SoftSignal.json');
const sepoliaPath = path.join(DEPLOYMENTS_DIR, 'sepolia', 'SoftSignal.json');

let localhostDeployment = null;
let sepoliaDeployment = null;
let abi = null;

// Read localhost deployment
if (fs.existsSync(localhostPath)) {
  localhostDeployment = JSON.parse(fs.readFileSync(localhostPath, 'utf-8'));
  abi = localhostDeployment.abi;
  console.log('📡 Found localhost deployment:', localhostDeployment.address);
} else {
  console.warn('⚠️  No localhost deployment found');
}

// Read sepolia deployment
if (fs.existsSync(sepoliaPath)) {
  sepoliaDeployment = JSON.parse(fs.readFileSync(sepoliaPath, 'utf-8'));
  if (!abi) {
    abi = sepoliaDeployment.abi;
  } else if (JSON.stringify(abi) !== JSON.stringify(sepoliaDeployment.abi)) {
    console.warn('⚠️  ABI mismatch between localhost and sepolia. Using localhost ABI.');
  }
  console.log('📡 Found sepolia deployment:', sepoliaDeployment.address);
} else {
  console.warn('⚠️  No sepolia deployment found');
}

if (!abi) {
  console.error('❌ No deployment found for SoftSignal. Run deployment first:');
  console.error('   cd fhevm-hardhat-template && npx hardhat deploy --network localhost');
  console.error('   or: npx hardhat deploy --network sepolia');
  process.exit(1);
}

try {
  // Generate ABI file
  const abiContent = `// Auto-generated by genabi.mjs
// Do not edit manually

export const SoftSignalABI = ${JSON.stringify(abi, null, 2)} as const;

export type SoftSignalABIType = typeof SoftSignalABI;
`;

  fs.writeFileSync(path.join(OUTPUT_DIR, 'SoftSignalABI.ts'), abiContent);
  console.log('✅ Generated SoftSignalABI.ts');

  // Generate addresses file
  const localhostAddress = localhostDeployment?.address || '';
  const sepoliaAddress = sepoliaDeployment?.address || '';
  
  const addressesContent = `// Auto-generated by genabi.mjs
// Do not edit manually

export const SoftSignalAddresses = {
  localhost: "${localhostAddress}",
  sepolia: "${sepoliaAddress}",
} as const;

export const getCurrentAddress = (chainId: number): string => {
  if (chainId === 31337) {
    return SoftSignalAddresses.localhost;
  } else if (chainId === 11155111) {
    return SoftSignalAddresses.sepolia;
  }
  throw new Error(\`Unsupported chain ID: \${chainId}\`);
};
`;

  fs.writeFileSync(path.join(OUTPUT_DIR, 'SoftSignalAddresses.ts'), addressesContent);
  console.log('✅ Generated SoftSignalAddresses.ts');
  console.log(`   Localhost: ${localhostAddress || '(not deployed)'}`);
  console.log(`   Sepolia: ${sepoliaAddress || '(not deployed)'}`);

  console.log('✨ ABI generation complete!');
} catch (error) {
  console.error('❌ Error generating ABIs:', error.message);
  process.exit(1);
}

